# semantic_model_validation/test_semantic_accuracy.py
# ─────────────────────────────────────────────────────────────
# Tests that validate AI-generated semantic model accuracy.
# Semantic models define what business data means in context.
# If the AI misunderstands business context, every downstream
# agent, report, and insight built on top of it will be wrong.
# ─────────────────────────────────────────────────────────────

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from deepeval import assert_test
from deepeval.metrics import AnswerRelevancyMetric, HallucinationMetric
from deepeval.test_case import LLMTestCase
from conftest import groq_model


class TestBusinessDefinitionAccuracy:
    """
    Tests that AI-generated business definitions
    are accurate, relevant, and contextually correct.
    A wrong business definition silently corrupts
    every metric, report, and insight built on top of it.
    """

    def test_mrr_definition_is_accurate(self):
        """
        Monthly Recurring Revenue definition generated
        by an AI agent must be business-accurate.
        """
        test_case = LLMTestCase(
            input="Define the business metric: Monthly Recurring Revenue",
            actual_output="MRR is the total predictable revenue a company expects to receive every month from active subscriptions.",
            expected_output="Should accurately define MRR as predictable monthly subscription revenue."
        )
        metric = AnswerRelevancyMetric(threshold=0.8, model=groq_model)
        assert_test(test_case, [metric])

    def test_churn_rate_definition_is_accurate(self):
        """
        Churn rate definition generated by an AI agent
        must correctly describe customer loss measurement.
        """
        test_case = LLMTestCase(
            input="Define the business metric: Customer Churn Rate",
            actual_output="Churn rate is the percentage of customers who stop using a service during a given time period.",
            expected_output="Should accurately define churn rate as the rate at which customers leave."
        )
        metric = AnswerRelevancyMetric(threshold=0.8, model=groq_model)
        assert_test(test_case, [metric])

    def test_customer_entity_definition_is_accurate(self):
        """
        Customer entity definition must correctly
        describe what a customer means in business context.
        """
        test_case = LLMTestCase(
            input="Define the business entity: Customer",
            actual_output="A customer is a person or organisation that purchases products or services from the business.",
            expected_output="Should accurately define a customer as a buyer of products or services."
        )
        metric = AnswerRelevancyMetric(threshold=0.8, model=groq_model)
        assert_test(test_case, [metric])


class TestSemanticModelHallucination:
    """
    Tests that AI agents do not invent business rules,
    formulas, or definitions that do not exist in context.
    Hallucinated business logic is extremely dangerous —
    it gets embedded into data products and reports silently.
    """

    def test_metric_formula_not_invented(self):
        """
        AI must only use the formula provided in context.
        Inventing a different formula corrupts all
        downstream calculations built on this metric.
        """
        test_case = LLMTestCase(
            input="What is the formula for calculating Net Revenue Retention?",
            actual_output="NRR = (Starting MRR + Expansion MRR - Churned MRR) / Starting MRR x 100",
            expected_output="Should use only the formula provided in the context.",
            context=[
                "Net Revenue Retention formula: (Starting MRR + Expansion - Churn) / Starting MRR * 100"
            ]
        )
        metric = HallucinationMetric(threshold=0.5, model=groq_model)
        assert_test(test_case, [metric])

    def test_business_rule_not_invented(self):
        """
        AI must not invent business rules that
        do not exist in the provided context.
        """
        test_case = LLMTestCase(
            input="What is the threshold for flagging a high-value customer?",
            actual_output="A high-value customer is defined as anyone spending over $10,000 annually.",
            expected_output="AI should state no threshold is defined in the context.",
            context=[
                "No high-value customer threshold has been defined for this business."
            ]
        )
        metric = HallucinationMetric(threshold=0.5, model=groq_model)
        assert_test(test_case, [metric])


class TestSemanticConsistency:
    """
    Tests that semantic model definitions are internally
    consistent and do not contradict each other.
    Contradictory definitions cause AI agents to produce
    conflicting answers depending on which definition they use.
    """

    def test_metric_name_matches_definition(self):
        """
        The metric name and its definition must be consistent.
        A metric named 'revenue' should not define customer count.
        """
        metric = {
            "name": "monthly_recurring_revenue",
            "definition": "Total predictable monthly revenue from active subscriptions"
        }

        revenue_keywords = ["revenue", "income", "earnings", "subscription"]
        definition_lower = metric["definition"].lower()

        has_revenue_concept = any(
            keyword in definition_lower
            for keyword in revenue_keywords
        )

        assert has_revenue_concept, \
            f"Metric '{metric['name']}' definition does not match its name"

    def test_entity_and_metrics_are_related(self):
        """
        Metrics assigned to an entity must be
        logically related to that entity.
        Customer metrics should measure customer behaviour
        not unrelated concepts like server uptime.
        """
        customer_entity = {
            "entity": "Customer",
            "metrics": [
                "total_revenue",
                "order_count",
                "churn_rate",
                "average_order_value"
            ]
        }

        unrelated_metrics = [
            "server_uptime",
            "cpu_usage",
            "memory_utilization",
            "deployment_frequency"
        ]

        for metric in customer_entity["metrics"]:
            assert metric not in unrelated_metrics, \
                f"Metric '{metric}' is not related to the Customer entity"
