# data_validation/test_data_quality.py
# ─────────────────────────────────────────────────────────────
# Tests that validate data quality before it reaches AI models.
# Core principle: clean data is the foundation of reliable AI.
# Garbage data in = garbage AI output.
# These tests catch data issues before they become AI failures.
# ─────────────────────────────────────────────────────────────

import pytest


class TestDataCompleteness:
    """
    Tests that all required fields exist and are not empty.
    Missing fields cause AI agents to make assumptions
    or hallucinate values — both dangerous in production.
    """

    def test_semantic_model_has_required_fields(self):
        """
        A semantic model definition must have all
        required fields before an AI agent can use it.
        """
        semantic_model = {
            "entity": "Customer",
            "definition": "A person who purchases products from the platform",
            "metrics": ["total_revenue", "order_count", "churn_rate"],
            "owner": "sales_team",
            "last_updated": "2026-05-17"
        }

        required_fields = ["entity", "definition", "metrics", "owner"]

        for field in required_fields:
            assert semantic_model.get(field), \
                f"Required field '{field}' is missing or empty"

    def test_data_catalog_entry_is_complete(self):
        """
        A data catalog entry generated by an AI agent
        must contain all required metadata fields.
        """
        catalog_entry = {
            "table_name": "orders",
            "description": "Contains all customer purchase orders",
            "columns": ["order_id", "customer_id", "amount", "created_at"],
            "owner": "data_engineering",
            "sensitivity": "confidential"
        }

        required_fields = [
            "table_name",
            "description",
            "columns",
            "owner",
            "sensitivity"
        ]

        for field in required_fields:
            assert catalog_entry.get(field), \
                f"Catalog entry missing required field: '{field}'"

    def test_metric_definition_is_complete(self):
        """
        A business metric definition must have
        a name, formula, owner, and description.
        Incomplete metric definitions break downstream
        AI analytics and reporting agents.
        """
        metric = {
            "name": "monthly_recurring_revenue",
            "formula": "SUM(subscription_amount) WHERE status = active",
            "owner": "finance_team",
            "description": "Total predictable monthly revenue from active subscriptions"
        }

        required_fields = ["name", "formula", "owner", "description"]

        for field in required_fields:
            assert metric.get(field), \
                f"Metric definition missing required field: '{field}'"


class TestDataTypes:
    """
    Tests that data fields have the correct types.
    Wrong data types cause silent failures in AI pipelines
    that are extremely hard to debug in production.
    """

    def test_metrics_is_a_list(self):
        """
        Metrics must be a list not a string.
        AI agents iterate over metrics — a string
        would cause silent incorrect behaviour.
        """
        model = {
            "entity": "Customer",
            "metrics": ["total_revenue", "order_count"]
        }
        assert isinstance(model["metrics"], list), \
            "Metrics must be a list not a string"
        assert len(model["metrics"]) > 0, \
            "Metrics list cannot be empty"

    def test_columns_is_a_list(self):
        """
        Table columns must be a list.
        """
        catalog_entry = {
            "table_name": "orders",
            "columns": ["order_id", "customer_id", "amount"]
        }
        assert isinstance(catalog_entry["columns"], list), \
            "Columns must be a list"
        assert len(catalog_entry["columns"]) > 0, \
            "Columns list cannot be empty"

    def test_entity_name_is_a_string(self):
        """
        Entity name must be a non-empty string.
        """
        model = {"entity": "Customer"}
        assert isinstance(model["entity"], str), \
            "Entity name must be a string"
        assert len(model["entity"]) > 0, \
            "Entity name cannot be empty"


class TestDataSensitivity:
    """
    Tests that sensitive information is handled correctly.
    AI agents must never expose PII or confidential data
    in definitions, descriptions, or catalog entries.
    """

    def test_no_pii_in_business_definition(self):
        """
        Business definitions must not contain
        personally identifiable information.
        """
        definition = "Customer revenue data excluding personal information fields"

        pii_keywords = [
            "password", "ssn", "social security",
            "credit_card", "secret", "private_key"
        ]

        for keyword in pii_keywords:
            assert keyword not in definition.lower(), \
                f"PII keyword '{keyword}' found in business definition"

    def test_sensitivity_classification_is_valid(self):
        """
        Every data catalog entry must have a valid
        sensitivity classification.
        Unknown sensitivity = unknown risk.
        """
        catalog_entry = {
            "table_name": "customers",
            "sensitivity": "confidential"
        }

        valid_classifications = [
            "public",
            "internal",
            "confidential",
            "restricted"
        ]

        assert catalog_entry["sensitivity"] in valid_classifications, \
            f"Invalid sensitivity classification: {catalog_entry['sensitivity']}"


class TestDataConsistency:
    """
    Tests that data is consistent across related fields.
    Inconsistent data causes AI agents to make
    contradictory statements or incorrect inferences.
    """

    def test_metric_names_are_snake_case(self):
        """
        Metric names must follow snake_case convention.
        Inconsistent naming breaks AI agent tool calls
        and downstream data pipeline references.
        """
        metrics = [
            "monthly_recurring_revenue",
            "customer_churn_rate",
            "average_order_value"
        ]

        for metric in metrics:
            assert metric == metric.lower(), \
                f"Metric '{metric}' is not lowercase"
            assert " " not in metric, \
                f"Metric '{metric}' contains spaces — use snake_case"

    def test_no_duplicate_column_names(self):
        """
        A table must not have duplicate column names.
        Duplicates cause AI agents to produce
        ambiguous or incorrect query results.
        """
        columns = ["order_id", "customer_id", "amount", "created_at"]

        assert len(columns) == len(set(columns)), \
            "Duplicate column names detected in table definition"
